spring:
    primary:
        datasource:
            url: jdbc:mysql://182.254.133.79:3306/eduroam_control_system?useSSL=false
            username: eduroam
            password: eduroam_control_system
            driver-class-name: com.mysql.jdbc.Driver


    radius:
        datasource:
            url: jdbc:mysql://localhost:3306/radius?useSSL=false
            username: root
            password: 123456
            driver-class-name: com.mysql.jdbc.Driver

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
              physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

server:
    port: 8081

logging:
    level:
        org.springframework.security: info


# 自定义的配置
jwt:
    header: Authorization
    secret: Secret
    expiration: 604800
